### PR TITLE
Fastlane Plugin - force_sign

### PR DESCRIPTION
**Pull request by portellaa**
* Created Plugin folder to add plugins into the repo
* Ran fastlane new_plugin
* Copied action to inside the plugin

@p4checo what are your thoughts on this? should we make this way or do you have a different idea?

### CODE REVIEW

**Comment by p4checo** [comment]
I think we should perhaps move this to a dedicated repo for the plugin, don't you agree?

**Comment by portellaa** [comment]
But then, we have to maintain two repos with most of the cases the same information no?
Perhaps we could separate this into branches and master only contains a README with information about the actions and links to those actions or plugins, no?

**Comment by p4checo** [comment]
I think `force_sign`(or however we end up calling it) would only live in the plugin repo from now on, and would leave this one 😛 
We can imagine that actions start here and eventually "graduate" to a plugin 😆, or that in the future we will work directly with plugins containing their own actions.

Also, if you take a look here https://docs.fastlane.tools/actions/#plugins all the plugins seem to have their own repo.

What do you say?

**Comment by portellaa** [comment]
I thought you were saying to have a repo like this, but called `fastlane-plugins` with the plugins. A repo per plugin seems fair, let's move to that approach. 😎
We really need to find a name for this 😝

**Comment by p4checo** [comment]
I'm going to close this issue since now we have created [cosigner](https://github.com/Mindera/fastlane-plugin-cosigner) ✍

**Comment by portellaa** [comment]
👍

**Pull request closed without merging**
